#!/usr/bin/env bash
#script to configure server for
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

IP_ADDR="127.0.0.2"
NEW_IP
sed -e s/127.0.0.1/$IP_ADDR/ /etc/hosts > ~/hosts.new
echo '8.8.8.8	facebook.com' >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
