#!/usr/bin/env bash
#script to configure server for
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

cp /etc/hosts /tmp/hosts.new
echo "127.0.0.2		localhost" > /tmp/hosts.new
echo "8.8.8.8		facebook.com" >> /tmp/hosts.new
cp -f /tmp/hosts.new /etc/hosts
