#!/usr/bin/env bash
# Installs and setsup nginx on to the server

#installs nginx and updates the package list
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Makes a custom html index file as below
echo "Hello World!" > /var/www/html/index.html
service nginx start
