#!/usr/bin/env bash
# Configure Nginx server 'redirect_me' to a custom 404 page

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start

# Error 404 Redirection script 
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "20i $new_string" /etc/nginx/sites-available/default

#reboot server
sudo service nginx restart
sudo service nginx reload
