#!/usr/bin/env bash
# script to configre Nginx for its HTTP response contains a custom header 'on web-01 and web-02'
# Custom HTTP header name must be X-Served-By
# Value of the custom HTTP header should be the hostname of the server Nginx is running on

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

sudo chmod -R 755 /var/www

echo 'Hello World!' |sudo tee  /var/www/html/index.html

echo "Ceci n'est pas une page" |sudo tee /var/www/html/custom_404.html

SERVER=$(hostname)

SERVER_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
		add_header X-Served-By '$SERVER';
                try_files \$uri \$uri/ =404;
        }
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

sudo /etc/init.d/nginx restart
