#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process

echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/holbertonscript.pid; exit" SIGQUIT

for (( ; ; ))
do 
    echo 'To infinity and beyond' 
    sleep 2
done
