#!/usr/bin/env bash
#creates file containing its PID,
#Displays statement while receiving signal
#Displays To infinity and beyond indefinitely
#terminates

echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/holbertonscript.pid; exit" SIGQUIT

for (( ; ; ))
do 
    echo 'To infinity and beyond' 
    sleep 2
done
