#!/usr/bin/env bash
#script displaying numbers from 1 to 100, with FizzBuzz, Fizz, and Buzz.

for i in {1..100}
do
	#Check if number is a multiple of 3 and 5
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	#Check if number is a multiple of 3
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	#Check if number is a multiple of 5
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	#Otherwise, display the number
	else
		echo $i
	fi
done
