#!/usr/bin/env bash
# A script displaying the visitor IP along with
#the HTTP status code from the Apache log file

# Use awk to retrieve the IP address and HTTP status from the Apache log file
echo "IP address  HTTP status code"
awk '{print $1, $9}' apache-access.log | sort | uniq
