#!/usr/bin/env bash
#A script displaying "Best School" 10 times, and Hi on the 9th iteration.

x=1

while [ $x -le 10 ]
do
    if [ $x -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((x++))
done
