#!/usr/bin/env bash
#A script displaying the content of the current directory in list format
#only displays the part of the name after the first dash

for curr in *; do
	echo "$curr" | cut -f2 -d'-'
done
